# Generated by Django 4.2.30 on 2026-06-23 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacture', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacture',
            options={'ordering': ['created_at'], 'verbose_name': 'Manufacture', 'verbose_name_plural': 'Manufactures'},
        ),
        migrations.AlterField(
            model_name='manufacture',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
